/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f303xc.h"


#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


// enable the clocks for desired peripherals (GPIOA, C and E)
void enable_clocks() {
	RCC->AHBENR |= RCC_AHBENR_GPIOAEN | RCC_AHBENR_GPIOBEN | RCC_AHBENR_GPIOCEN | RCC_AHBENR_GPIOEEN;
}

// initialise the discovery board I/O (just outputs: inputs are selected by default)
void initialise_board() {

	// get a pointer to the second half word of the MODER register (for outputs pe8-15)
	uint16_t *led_output_registers = ((uint16_t *)&(GPIOE->MODER)) + 1;
	*led_output_registers = 0x5555;
}


uint16_t ReadADC(uint32_t channel) {

	ADC1->SQR1 = 0;
	ADC1->SQR1 |= channel << ADC_SQR1_SQ1_Pos; // set the request for channel specified

	// request the process to start
	ADC1->CR |= ADC_CR_ADSTART;

	// Wait for the end of conversion
	while((ADC1->ISR &= ADC_ISR_EOS) != ADC_ISR_EOS);

	return ADC1->DR;
}

void ContinuousReadSingleChannelADC2() {

	// get a pointer to the location of the LEDs
	uint8_t *led_register = ((uint8_t*)&(GPIOE->ODR)) + 1;

	// enable the clock for ADC1
	RCC->AHBENR |= RCC_AHBENR_ADC12EN;

	// set to synchronise the ADC with the clock
	ADC12_COMMON->CCR |= ADC12_CCR_CKMODE_0;

	// ADEN must be = 0 for configuration (is the default)
	ADC2->CR &= ~ADC_CR_ADVREGEN; // clear voltage regulator enable
	ADC2->CR |= ADC_CR_ADVREGEN_0; // set ADVREGEN TO 01
	ADC2->CR &= ~ADC_CR_ADCALDIF; // clear bit to enable Single-ended-input

	// calibrate the ADC (self calibration routine)
	ADC2->CR |= ADC_CR_ADCAL;
	while((ADC2->CR & ADC_CR_ADCAL) == ADC_CR_ADCAL); // Waiting for the calibration to finish

	// select the channel, only one conversion so it goes in
	//  the first conversion slot (SQ1)
	//  and the L value should be 0 (L=0000 does one conversion only)
	ADC2->SQR1 = 0; // clear any existing channel requests
	ADC2->SQR1 |= 0x02 << ADC_SQR1_SQ1_Pos; // request channel 2
	ADC2->SQR1 |= 0x00 << ADC_SQR1_L_Pos; // set the number of channels to read

	// continuous mode
	ADC2->CFGR |= ADC_CFGR_CONT;

	// Enable ADC
	ADC2->CR |= ADC_CR_ADEN;

	while (ADC2->ISR == 0); //Wait the ADC to be ready.

	// request the process to start
	// only need once in continuous mode
	ADC2->CR |= ADC_CR_ADSTART;

	uint16_t value = 0;
	uint8_t scale = 0;

    /* Loop forever */
	for(;;) {

		// Wait for the end of conversion
		while(!(ADC2->ISR &= ADC_ISR_EOC));

		value = ADC2->DR;

		// read the value from ADC2->DR,
		// full range is 12 bits (0xFFF maximum)
		// divide the scale into 8 even partitions (for 8 leds)
		scale = value / (0xfff / 2);

		if (scale > 1) {
			scale = 1;
		}

		*led_register = 1 << scale ;
	}
}

void ContinuousReadSingleChannelADC3() {

	// get a pointer to the location of the LEDs
	uint8_t *led_register = ((uint8_t*)&(GPIOE->ODR)) + 1;

	// enable the clock for ADC1
	RCC->AHBENR |= RCC_AHBENR_ADC34EN;

	// set to synchronise the ADC with the clock
	ADC34_COMMON->CCR |= ADC34_CCR_CKMODE_0;

	// ADEN must be = 0 for configuration (is the default)
	ADC3->CR &= ~ADC_CR_ADVREGEN; // clear voltage regulator enable
	ADC3->CR |= ADC_CR_ADVREGEN_0; // set ADVREGEN TO 01
	ADC3->CR &= ~ADC_CR_ADCALDIF; // clear bit to enable Single-ended-input

	// calibrate the ADC (self calibration routine)
	ADC3->CR |= ADC_CR_ADCAL;
	while((ADC3->CR & ADC_CR_ADCAL) == ADC_CR_ADCAL); // Waiting for the calibration to finish

	// select the channel, only one conversion so it goes in
	//  the first conversion slot (SQ1)
	//  and the L value should be 0 (L=0000 does one conversion only)
	ADC3->SQR1 = 0; // clear any existing channel requests
	ADC3->SQR1 |= 0x01 << ADC_SQR1_SQ1_Pos; // request channel 1
	ADC3->SQR1 |= 0x00 << ADC_SQR1_L_Pos; // set the number of channels to read

	// continuous mode
	ADC3->CFGR |= ADC_CFGR_CONT;

	// Enable ADC
	ADC3->CR |= ADC_CR_ADEN;

	while (ADC3->ISR == 0); //Wait the ADC to be ready.

	// request the process to start
	// only need once in continuous mode
	ADC3->CR |= ADC_CR_ADSTART;

	uint16_t value = 0;
	uint8_t scale = 0;

    /* Loop forever */
	for(;;) {

		// Wait for the end of conversion
		while(!(ADC3->ISR &= ADC_ISR_EOC));

		value = ADC3->DR;

		// read the value from ADC3->DR,
		// full range is 12 bits (0xFFF maximum)
		// divide the scale into 8 even partitions (for 8 leds)
		scale = value / (0xfff / 8);

		if (scale > 7) {
			scale = 7;
		}

		*led_register = 1 << scale ;
	}
}


void SingleReadMultiChannelADC() {

	// get a pointer to the location of the LEDs
	uint8_t *led_register = ((uint8_t*)&(GPIOE->ODR)) + 1;

	// enable the clock for ADC1
	RCC->AHBENR |= RCC_AHBENR_ADC12EN;

	// set to synchronise the ADC with the clock
	ADC12_COMMON->CCR |= ADC12_CCR_CKMODE_0;

	// ADEN must be = 0 for configuration (is the default)
	ADC1->CR &= ~ADC_CR_ADVREGEN; // clear voltage regulator enable
	ADC1->CR |= ADC_CR_ADVREGEN_0; // set ADVREGEN TO 01
	ADC1->CR &= ~ADC_CR_ADCALDIF; // clear bit to enable Single-ended-input

	// calibrate the ADC (self calibration routine)
	ADC1->CR |= ADC_CR_ADCAL;
	while((ADC1->CR & ADC_CR_ADCAL) == ADC_CR_ADCAL); // Waiting for the calibration to finish

/*
 	// can change the sampling time (longer is more accurate)
	ADC1->SMPR1 |= 7 << ADC_SMPR1_SMP0_Pos;
	ADC1->SMPR1 |= 7 << ADC_SMPR1_SMP1_Pos;
	ADC1->SMPR1 |= 7 << ADC_SMPR1_SMP2_Pos;
*/

	// We want to read from two channels each sequence
	//  the first channel goes in SQ1
	//  the second channel goes in SQ2
	//  the number of channels to read = 2, so the L value is 1
	ADC1->SQR1 = 0;
	ADC1->SQR1 |= 0x02 << ADC_SQR1_SQ1_Pos; // set the request for channel 2
	ADC1->SQR1 |= 0x03 << ADC_SQR1_SQ2_Pos; // set the request for channel 3
	ADC1->SQR1 |= 0x04 << ADC_SQR1_SQ3_Pos; // set the request for channel 4
	ADC1->SQR1 |= 0x04 << ADC_SQR1_L_Pos; // set the number of channels to read //

	// single shot mode
	ADC1->CFGR &= ~ADC_CFGR_CONT;

	// Enable the ADC
	ADC1->CR |= ADC_CR_ADEN;

	// Wait the ADC to be ready.
	while (ADC1->ISR == 0);

	uint16_t value_1 = 0;
	uint16_t value_2 = 0;
	uint16_t value_3 = 0;

    /* Loop forever */
	for(;;) {

		// request the process to start
		ADC1->CR |= ADC_CR_ADSTART;

		// Wait for the end of the first conversion
		while(!(ADC1->ISR & ADC_ISR_EOC));

		// read the first value
		value_1 = ADC1->DR;

		while(!(ADC1->ISR & ADC_ISR_EOC));

		// read the second value
		value_2 = ADC1->DR;

		while(!(ADC1->ISR & ADC_ISR_EOC));

		// read the second value
		value_3 = ADC1->DR;

		// reset the sequence flag
		ADC1->ISR |= ADC_ISR_EOS;


		// full range is 12 bits (0xFFF maximum)
		// divide the scale into 4 even partitions (for 4 leds)
		uint8_t scale_1 = value_1 / (0xfff / 2);

		if (scale_1 > 1) {
			scale_1 = 1;
		}

		// full range is 12 bits (0xFFF maximum)
		// divide the scale into 4 even partitions (for 4 leds)
		uint8_t scale_2 = value_2 / (0xfff / 2);

		if (scale_2 > 1) {
			scale_2 = 1;
		}

		uint8_t scale_3 = value_3 / (0xfff / 2);

		if (scale_3 > 1) {
			scale_3 = 1;
		}

		// draw the state of channel 2 in the first 4 LEDs
		// and the state of channel 3 in the second set of 4 LEDs
		*led_register = 1 << scale_1 | 1 << (scale_2 + 2) | 1 << (scale_3 + 4);
	}
}

void SingleReadMultiChannelADC2() {

	// get a pointer to the location of the LEDs
	uint8_t *led_register = ((uint8_t*)&(GPIOE->ODR)) + 1;

	// enable the clock for ADC1
	RCC->AHBENR |= RCC_AHBENR_ADC12EN;

	// set to synchronise the ADC with the clock
	ADC12_COMMON->CCR |= ADC12_CCR_CKMODE_0;

	// ADEN must be = 0 for configuration (is the default)
	ADC2->CR &= ~ADC_CR_ADVREGEN; // clear voltage regulator enable
	ADC2->CR |= ADC_CR_ADVREGEN_0; // set ADVREGEN TO 01
	ADC2->CR &= ~ADC_CR_ADCALDIF; // clear bit to enable Single-ended-input

	// calibrate the ADC (self calibration routine)
	ADC2->CR |= ADC_CR_ADCAL;
	while((ADC2->CR & ADC_CR_ADCAL) == ADC_CR_ADCAL); // Waiting for the calibration to finish

/*
 	// can change the sampling time (longer is more accurate)
	ADC1->SMPR1 |= 7 << ADC_SMPR1_SMP0_Pos;
	ADC1->SMPR1 |= 7 << ADC_SMPR1_SMP1_Pos;
	ADC1->SMPR1 |= 7 << ADC_SMPR1_SMP2_Pos;
*/

	// We want to read from two channels each sequence
	//  the first channel goes in SQ1
	//  the second channel goes in SQ2
	//  the number of channels to read = 2, so the L value is 1
	ADC2->SQR1 = 0;
	ADC2->SQR1 |= 0x01 << ADC_SQR1_SQ1_Pos; // set the request for channel 2
	ADC2->SQR1 |= 0x02 << ADC_SQR1_SQ2_Pos; // set the request for channel 3
	ADC2->SQR1 |= 0x03 << ADC_SQR1_SQ3_Pos; // set the request for channel 4
	ADC2->SQR1 |= 0x04 << ADC_SQR1_SQ4_Pos; // set the request for channel 4
	ADC2->SQR1 |= 0x08 << ADC_SQR1_L_Pos; // set the number of channels to read //keep this at the number of channels we want to read plus 2

	// single shot mode
	ADC2->CFGR &= ~ADC_CFGR_CONT;

	// Enable the ADC
	ADC2->CR |= ADC_CR_ADEN;

	// Wait the ADC to be ready.
	while (ADC2->ISR == 0);

	uint16_t value_1 = 0;
	uint16_t value_2 = 0;
	uint16_t value_3 = 0;
	uint16_t value_4 = 0;

    /* Loop forever */
	for(;;) {

		// request the process to start
		ADC2->CR |= ADC_CR_ADSTART;

		// Wait for the end of the first conversion
		while(!(ADC2->ISR & ADC_ISR_EOC));

		// read the first value
		value_1 = ADC2->DR;

		while(!(ADC2->ISR & ADC_ISR_EOC));

		// read the second value
		value_2 = ADC2->DR;

		while(!(ADC2->ISR & ADC_ISR_EOC));

		// read the second value
		value_3 = ADC2->DR;

		while(!(ADC2->ISR & ADC_ISR_EOC));

		// read the second value
		value_4 = ADC2->DR;

		// reset the sequence flag
		ADC2->ISR |= ADC_ISR_EOS;


		// full range is 12 bits (0xFFF maximum)
		// divide the scale into 4 even partitions (for 4 leds)
		uint8_t scale_1 = value_1 / (0xfff / 2);

		if (scale_1 > 1) {
			scale_1 = 1;
		}

		// full range is 12 bits (0xFFF maximum)
		// divide the scale into 4 even partitions (for 4 leds)
		uint8_t scale_2 = value_2 / (0xfff / 2);

		if (scale_2 > 1) {
			scale_2 = 1;
		}

		uint8_t scale_3 = value_3 / (0xfff / 2);

		if (scale_3 > 1) {
			scale_3 = 1;
		}

		uint8_t scale_4 = value_4 / (0xfff / 2);

		if (scale_4 > 1) {
			scale_4 = 1;
		}

		// draw the state of channel 2 in the first 4 LEDs
		// and the state of channel 3 in the second set of 4 LEDs
		*led_register = 1 << scale_1 | 1 << (scale_2 + 2) | 1 << (scale_3 + 4) | 1 << (scale_4 + 6);
	}
}




int main(void)
{
	enable_clocks();
	initialise_board();

	// check if the button is pressed, determine which mode
	//  to enter.
	if ((GPIOA->IDR & 0x01) == 0)
		SingleReadMultiChannelADC2();
	else
		ContinuousReadSingleChannelADC3();
}
