/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "ptu_definitions.h"
#include "ptu_i2c.h"
#include "serial.h"
#include "serialise.h"
#include "adc.h"
#include "gameplay.h"
#include "timer.h"
#include "led.h"
#include "stdint.h"
#include "stm32f303xc.h"
#include "math.h"


#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif




int main(void)
{


	Phase1();


	// check if the button is pressed, determine which mode
	//  to enter.
	/*
	if ((GPIOA->IDR & 0x01) == 0){
		//SingleReadMultiChannelADC2();


	}
	else{
		ContinuousReadSingleChannel(&ADC3_Port);

	}*/

	for(;;);
}

