/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f303xc.h"
#include <stdlib.h>
#include <stdio.h>
#include "servo.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

struct joystick_coordinates {
	uint16_t x_coordinate;
	uint16_t y_coordinate;
};

void InitialiseADC() {

	// enable the clock for ADC1
	RCC->AHBENR |= RCC_AHBENR_ADC12EN;

	// set to synchronise the ADC with the clock
	ADC12_COMMON->CCR |= ADC12_CCR_CKMODE_0;

	// ADEN must be = 0 for configuration (is the default)
	ADC1->CR &= ~ADC_CR_ADVREGEN; // clear voltage regulator enable
	ADC1->CR |= ADC_CR_ADVREGEN_0; // set ADVREGEN TO 01
	ADC1->CR &= ~ADC_CR_ADCALDIF; // clear bit to enable Single-ended-input

	// calibrate the ADC (self calibration routine)
	ADC1->CR |= ADC_CR_ADCAL;
	while((ADC1->CR & ADC_CR_ADCAL) == ADC_CR_ADCAL); // Waiting for the calibration to finish

	// select the channel, only one conversion so it goes in
	//  the first conversion slot (SQ1)
	//  and the L value should be 0 (L=0000 does one conversion only)
	ADC1->SQR1 = 0; // clear any existing channel requests
	ADC1->SQR1 |= 0x02 << ADC_SQR1_SQ1_Pos; // request channel 2
	ADC1->SQR1 |= 0x00 << ADC_SQR1_L_Pos; // set the number of channels to read

	// continuous mode
	ADC1->CFGR |= ADC_CFGR_CONT;

	// Enable ADC
	ADC1->CR |= ADC_CR_ADEN;

	while (ADC1->ISR == 0); //Wait the ADC to be ready.

	// request the process to start
	// only need once in continuous mode
	ADC1->CR |= ADC_CR_ADSTART;

	ADC2->CR &= ~ADC_CR_ADVREGEN; // clear voltage regulator enable
	ADC2->CR |= ADC_CR_ADVREGEN_0; // set ADVREGEN TO 01
	ADC2->CR &= ~ADC_CR_ADCALDIF; // clear bit to enable Single-ended-input

	// calibrate the ADC (self calibration routine)
	ADC2->CR |= ADC_CR_ADCAL;
	while((ADC2->CR & ADC_CR_ADCAL) == ADC_CR_ADCAL); // Waiting for the calibration to finish

	// select the channel, only one conversion so it goes in
	//  the first conversion slot (SQ1)
	//  and the L value should be 0 (L=0000 does one conversion only)
	ADC2->SQR1 = 0; // clear any existing channel requests
	ADC2->SQR1 |= 0x02 << ADC_SQR1_SQ1_Pos; // request channel 2
	ADC2->SQR1 |= 0x00 << ADC_SQR1_L_Pos; // set the number of channels to read

	// continuous mode
	ADC2->CFGR |= ADC_CFGR_CONT;

	// Enable ADC
	ADC2->CR |= ADC_CR_ADEN;

	while (ADC2->ISR == 0); //Wait the ADC to be ready.

	// request the process to start
	// only need once in continuous mode
	ADC2->CR |= ADC_CR_ADSTART;

}

void get_joystick_values(struct joystick_coordinates* joystick) {
	uint16_t value_1 = 0;
	uint16_t value_2 = 0;

	while(!(ADC1->ISR &= ADC_ISR_EOC));
	value_1 = ADC1->DR;

	while(!(ADC2->ISR &= ADC_ISR_EOC));
	value_2 = ADC2->DR;

	uint16_t mapped_value_1 = (1000.0 / (3650.0- 2800.0)) * (value_1 - 2800.0);

	uint16_t mapped_value_2 = (1000.0 / (3900.0- 2200.0)) * (value_2 - 2200.0);
	mapped_value_2 = 1000 - mapped_value_2;
	if (mapped_value_2 > 1000) {
		mapped_value_2 = 0;
	}
	joystick->x_coordinate = mapped_value_1;
	joystick->y_coordinate = mapped_value_2;

}

void joystickToServos(struct joystick_coordinates* joystick) {
	// get joystick values

	// map values
	float x_pos = (float)(joystick->x_coordinate)/1000;
	float y_pos = (float)(joystick->y_coordinate)/1000;

	float x_pos_invert = 1-x_pos + 0.15;
	if (x_pos_invert > 1) {
		x_pos_invert = (float) 1.0;
	}
	else if (x_pos_invert < 0) {
		x_pos_invert = (float) 0.0;
	}

	// send axis 1 to position
	servoGoToFractionalPosition(&Servo1, x_pos + 0.1);
	servoGoToFractionalPosition(&Servo2, x_pos_invert - 0.1);  // inverse

	// send axis 2 to position
	servoGoToFractionalPosition(&Servo3, y_pos-0.1);
	servoGoToFractionalPosition(&Servo4, 1-y_pos);  // inverse
}


void run() {
	InitialiseADC();
	struct joystick_coordinates joystick = {0, 0};
	for(;;) {
		get_joystick_values(&joystick);
		joystickToServos(&joystick);
	}
}
